"""JAR by reference (RFC 9101): a signed request object, fetched and applied.

The load-bearing property is NOT that the feature works -- it is the SSRF guard.
An authorize endpoint that fetches a caller-supplied URL is a request-forgery
primitive unless it reaches only origins the tenant already trusted, so the
refusals here matter more than the success.

WHAT MAKES THIS EXTERNAL. The request object is a real RS256 JWT produced by
PyJWT over a key generated by `cryptography`, registered on the app the way an
admin registers a certificate. Nothing in this file hand-rolls a signature, so
the emulator is verifying a real library's output against a key it was given
through its own admin surface.

THE POSITIVE CASE IS LOAD-BEARING TOO. Every refusal below would still pass if
the feature simply rejected everything, so the suite also proves an object from
a trusted origin is fetched AND that its parameters actually override the query
string -- `state` differs between the two, and the object's value is the one
that comes back.
"""

import http.server
import json
import os
import ssl
import sys
import threading
import urllib.error
import urllib.parse
import urllib.request

import jwt
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

ORIGIN = os.environ["EMU_ORIGIN"]
TENANT = os.environ["EMU_TENANT"]
CERT = os.environ["EMU_CERT"]
AUTHORIZE = f"{ORIGIN}/{TENANT}/oauth2/v2.0/authorize"
ADMIN = f"{ORIGIN}/admin/api/apps"
SPA_ID = "189c7070-78a3-4c13-aa18-20a2ca5755ca"
KID = "jar-key"

ssl_ctx = ssl.create_default_context(cafile=CERT)
ssl_ctx.check_hostname = False
failures = []


def check(name, cond, extra=""):
    print(f"   {'ok  ' if cond else 'FAIL'}  {name}{'' if cond else ': ' + str(extra)[:200]}")
    if not cond:
        failures.append(name)


def post_json(url, body):
    data = json.dumps(body).encode()
    req = urllib.request.Request(url, data=data, method="POST")
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, context=ssl_ctx, timeout=20) as r:
            return r.status, json.loads(r.read() or b"{}")
    except urllib.error.HTTPError as e:
        return e.code, {"raw": e.read()[:200].decode("utf-8", "replace")}


def authorize(params):
    """GET /authorize without following the redirect, so the 302 is observable."""
    url = AUTHORIZE + "?" + urllib.parse.urlencode(params)

    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *_a, **_k):
            return None

    opener = urllib.request.build_opener(
        urllib.request.HTTPSHandler(context=ssl_ctx), NoRedirect
    )
    try:
        with opener.open(url, timeout=20) as r:
            return r.status, r.headers.get("Location", ""), r.read()[:2000].decode("utf-8", "replace")
    except urllib.error.HTTPError as e:
        return e.code, e.headers.get("Location", ""), e.read()[:2000].decode("utf-8", "replace")


class Serve(http.server.BaseHTTPRequestHandler):
    """Serves the request object, and a redirect, so both paths are testable."""

    body = b""

    def do_GET(self):
        if self.path.startswith("/redirect"):
            # A 302 towards the trusted origin. Following it is how an origin
            # allowlist gets bypassed, so the emulator must not.
            self.send_response(302)
            self.send_header("Location", "/obj")
            self.end_headers()
            return
        self.send_response(200)
        self.send_header("Content-Type", "application/jwt")
        self.end_headers()
        self.wfile.write(self.body)

    def log_message(self, *_a):
        pass


def start_server(body):
    handler = type("H", (Serve,), {"body": body})
    srv = http.server.HTTPServer(("127.0.0.1", 0), handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv, f"http://127.0.0.1:{srv.server_address[1]}"


def main():
    print("JAR by reference against", AUTHORIZE)

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    pub_pem = key.public_key().public_bytes(
        serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
    ).decode()
    status, body = post_json(f"{ADMIN}/{SPA_ID}/keyCredentials",
                             {"publicKey": pub_pem, "displayName": "jar"})
    check("app signing key registered", status in (200, 201), f"{status} {body}")

    # The object carries a state the query string does NOT, so "the object was
    # applied" is distinguishable from "the query was used".
    obj = jwt.encode(
        {"iss": SPA_ID, "response_type": "code", "scope": "openid",
         "redirect_uri": "https://localhost:3000", "state": "from-object"},
        key, algorithm="RS256", headers={"kid": KID},
    ).encode()

    trusted_srv, trusted = start_server(obj)
    foreign_srv, foreign = start_server(obj)
    try:
        # 1. THE GUARD. An origin the tenant never trusted for this app.
        status, _, page = authorize({"client_id": SPA_ID, "request_uri": foreign + "/obj"})
        check(f"untrusted origin refused ({status})", status == 400, page)
        check("the refusal names the reason",
              "registered redirect-URI origin" in page, page)

        # 2. Trust the origin the way an admin would, then it must work.
        status, body = post_json(f"{ADMIN}/{SPA_ID}/redirectUris",
                                 {"uri": trusted + "/cb", "type": "web"})
        check("origin trusted via a registered redirect URI", status in (200, 201),
              f"{status} {body}")

        status, location, page = authorize({
            "client_id": SPA_ID, "request_uri": trusted + "/obj",
            # Deliberately different from the object's value.
            "state": "from-query",
        })
        check(f"trusted origin accepted ({status})", status in (200, 302), page[:200])
        applied = "from-object" in (location + page)
        check("the object's parameters overrode the query", applied,
              f"location={location[:120]} page={page[:120]}")

        # 3. Redirects are not followed, even towards a trusted origin: a 302
        #    is exactly how an allowlist gets bypassed.
        status, _, page = authorize({"client_id": SPA_ID, "request_uri": foreign + "/redirect"})
        check(f"a redirecting request_uri is not followed ({status})", status == 400, page)
    finally:
        trusted_srv.shutdown()
        foreign_srv.shutdown()

    if failures:
        print(f"\n{len(failures)} failure(s): {', '.join(failures)}")
        sys.exit(1)
    print("\nJAR: PyJWT-signed object fetched from a trusted origin and applied; "
          "untrusted origin and redirect both refused")


if __name__ == "__main__":
    main()
